name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create required directories
      run: |
        mkdir -p static/uploads
        mkdir -p static/processed
        touch static/uploads/.gitkeep
        touch static/processed/.gitkeep
    - name: Run tests
      run: |
        pytest -v test_app.py